"""
Pre-configured sources registry for 25-30 global and regional news feeds.
All feeds use official, public RSS/Atom feeds or APIs.
"""

SOURCE_REGISTRY = [
    # Global Major News
    {
        "id": "bbc-world",
        "name": "BBC News (World)",
        "type": "RSS",
        "base_url": "https://www.bbc.com",
        "feed_url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "country": "UK",
        "language": "en",
        "category": "World",
        "fetch_interval": 10,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/4/41/BBC_Logo_2021.svg"
    },
    {
        "id": "bbc-tech",
        "name": "BBC Technology",
        "type": "RSS",
        "base_url": "https://www.bbc.com",
        "feed_url": "https://feeds.bbci.co.uk/news/technology/rss.xml",
        "country": "UK",
        "language": "en",
        "category": "Technology",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/4/41/BBC_Logo_2021.svg"
    },
    {
        "id": "bbc-business",
        "name": "BBC Business",
        "type": "RSS",
        "base_url": "https://www.bbc.com",
        "feed_url": "https://feeds.bbci.co.uk/news/business/rss.xml",
        "country": "UK",
        "language": "en",
        "category": "Business",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/4/41/BBC_Logo_2021.svg"
    },
    {
        "id": "bbc-sport",
        "name": "BBC Sport",
        "type": "RSS",
        "base_url": "https://www.bbc.com",
        "feed_url": "https://feeds.bbci.co.uk/sport/rss.xml",
        "country": "UK",
        "language": "en",
        "category": "Sport",
        "fetch_interval": 10,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/4/41/BBC_Logo_2021.svg"
    },
    {
        "id": "guardian-world",
        "name": "The Guardian (World)",
        "type": "RSS",
        "base_url": "https://www.theguardian.com",
        "feed_url": "https://www.theguardian.com/world/rss",
        "country": "UK",
        "language": "en",
        "category": "World",
        "fetch_interval": 15,
        "rate_limit": 200,
        "logo_url": "https://assets.guim.co.uk/images/guardian-logo-160.png"
    },
    {
        "id": "aljazeera-all",
        "name": "Al Jazeera English",
        "type": "RSS",
        "base_url": "https://www.aljazeera.com",
        "feed_url": "https://www.aljazeera.com/xml/rss/all.xml",
        "country": "Qatar",
        "language": "en",
        "category": "World",
        "fetch_interval": 10,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Aljazeera_eng.svg/200px-Aljazeera_eng.svg.png"
    },
    {
        "id": "reuters-world",
        "name": "Reuters News",
        "type": "RSS",
        "base_url": "https://www.reuters.com",
        "feed_url": "https://www.reutersagency.com/feed/?best-topics=world&post_type=best",
        "country": "Global",
        "language": "en",
        "category": "World",
        "fetch_interval": 10,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Reuters_Logo.svg"
    },
    {
        "id": "cnn-top",
        "name": "CNN Top Stories",
        "type": "RSS",
        "base_url": "https://www.cnn.com",
        "feed_url": "http://rss.cnn.com/rss/edition.rss",
        "country": "US",
        "language": "en",
        "category": "World",
        "fetch_interval": 10,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/CNN.svg"
    },
    {
        "id": "dw-world",
        "name": "Deutsche Welle (DW)",
        "type": "RSS",
        "base_url": "https://www.dw.com",
        "feed_url": "https://rss.dw.com/rdf/rss-en-all",
        "country": "Germany",
        "language": "en",
        "category": "World",
        "fetch_interval": 20,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/6/67/Deutsche_Welle_logo.svg"
    },
    {
        "id": "france24-en",
        "name": "France 24 English",
        "type": "RSS",
        "base_url": "https://www.france24.com",
        "feed_url": "https://www.france24.com/en/rss",
        "country": "France",
        "language": "en",
        "category": "World",
        "fetch_interval": 20,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/en/8/87/France_24_logo.svg"
    },
    {
        "id": "npr-news",
        "name": "NPR News",
        "type": "RSS",
        "base_url": "https://www.npr.org",
        "feed_url": "https://feeds.npr.org/1001/rss.xml",
        "country": "US",
        "language": "en",
        "category": "World",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/d/d7/National_Public_Radio_logo.svg"
    },

    # India & South Asia Sources
    {
        "id": "ndtv-top",
        "name": "NDTV News Top Stories",
        "type": "RSS",
        "base_url": "https://www.ndtv.com",
        "feed_url": "https://feeds.feedburner.com/ndtvnews-top-stories",
        "country": "India",
        "language": "en",
        "category": "India",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/f/f5/NDTV_logo.svg"
    },
    {
        "id": "ndtv-india",
        "name": "NDTV India News",
        "type": "RSS",
        "base_url": "https://www.ndtv.com",
        "feed_url": "https://feeds.feedburner.com/ndtvnews-india-news",
        "country": "India",
        "language": "en",
        "category": "India",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/f/f5/NDTV_logo.svg"
    },
    {
        "id": "toi-world",
        "name": "Times of India (World)",
        "type": "RSS",
        "base_url": "https://timesofindia.indiatimes.com",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
        "country": "India",
        "language": "en",
        "category": "World",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://static.toiimg.com/photo/79638690.cms"
    },
    {
        "id": "toi-india",
        "name": "Times of India (India)",
        "type": "RSS",
        "base_url": "https://timesofindia.indiatimes.com",
        "feed_url": "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
        "country": "India",
        "language": "en",
        "category": "India",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://static.toiimg.com/photo/79638690.cms"
    },
    {
        "id": "hindu-national",
        "name": "The Hindu (National)",
        "type": "RSS",
        "base_url": "https://www.thehindu.com",
        "feed_url": "https://www.thehindu.com/news/national/feeder/default.rss",
        "country": "India",
        "language": "en",
        "category": "India",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/4/41/The_Hindu_Logo.svg"
    },
    {
        "id": "indian-express",
        "name": "The Indian Express",
        "type": "RSS",
        "base_url": "https://indianexpress.com",
        "feed_url": "https://indianexpress.com/feed/",
        "country": "India",
        "language": "en",
        "category": "India",
        "fetch_interval": 20,
        "rate_limit": 100,
        "logo_url": "https://images.indianexpress.com/2021/04/ie-logo-1.png"
    },

    # Technology & AI
    {
        "id": "techcrunch",
        "name": "TechCrunch",
        "type": "RSS",
        "base_url": "https://techcrunch.com",
        "feed_url": "https://techcrunch.com/feed/",
        "country": "US",
        "language": "en",
        "category": "Technology",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/b/b9/TechCrunch_logo.svg"
    },
    {
        "id": "the-verge",
        "name": "The Verge",
        "type": "RSS",
        "base_url": "https://www.theverge.com",
        "feed_url": "https://www.theverge.com/rss/index.xml",
        "country": "US",
        "language": "en",
        "category": "Technology",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/af/The_Verge_2022_logo.svg"
    },
    {
        "id": "ars-technica",
        "name": "Ars Technica",
        "type": "RSS",
        "base_url": "https://arstechnica.com",
        "feed_url": "https://feeds.arstechnica.com/arstechnica/index",
        "country": "US",
        "language": "en",
        "category": "Technology",
        "fetch_interval": 20,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/0/07/Ars_Technica_logo_%282016%29.svg"
    },
    {
        "id": "wired-tech",
        "name": "Wired",
        "type": "RSS",
        "base_url": "https://www.wired.com",
        "feed_url": "https://www.wired.com/feed/rss",
        "country": "US",
        "language": "en",
        "category": "Technology",
        "fetch_interval": 20,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Wired_wordmark.svg"
    },

    # Business & Economy
    {
        "id": "financial-times",
        "name": "Financial Times (World)",
        "type": "RSS",
        "base_url": "https://www.ft.com",
        "feed_url": "https://www.ft.com/world?format=rss",
        "country": "UK",
        "language": "en",
        "category": "Business",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Financial_Times_corporate_logo.svg"
    },
    {
        "id": "cnbc-top",
        "name": "CNBC International",
        "type": "RSS",
        "base_url": "https://www.cnbc.com",
        "feed_url": "https://search.cnbc.com/rs/search/view.html?partnerId=2000&keywords=business&sort=date",
        "country": "US",
        "language": "en",
        "category": "Business",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/e/e3/CNBC_logo.svg"
    },
    {
        "id": "economic-times",
        "name": "The Economic Times",
        "type": "RSS",
        "base_url": "https://economictimes.indiatimes.com",
        "feed_url": "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
        "country": "India",
        "language": "en",
        "category": "Business",
        "fetch_interval": 15,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/5/53/The_Economic_Times_logo.svg"
    },

    # Science, Health & Earth
    {
        "id": "nature-news",
        "name": "Nature News",
        "type": "RSS",
        "base_url": "https://www.nature.com",
        "feed_url": "https://www.nature.com/nature.rss",
        "country": "Global",
        "language": "en",
        "category": "Science",
        "fetch_interval": 30,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/1/14/Nature_journal_logo.svg"
    },
    {
        "id": "scientific-american",
        "name": "Scientific American",
        "type": "RSS",
        "base_url": "https://www.scientificamerican.com",
        "feed_url": "http://rss.sciam.com/ScientificAmerican-Global",
        "country": "US",
        "language": "en",
        "category": "Science",
        "fetch_interval": 30,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/7/77/Scientific_American_logo.svg"
    },
    {
        "id": "who-news",
        "name": "World Health Organization (WHO)",
        "type": "RSS",
        "base_url": "https://www.who.int",
        "feed_url": "https://www.who.int/rss-feeds/news-english.xml",
        "country": "Global",
        "language": "en",
        "category": "Health",
        "fetch_interval": 30,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/c/c2/WHO_logo.svg"
    },

    # Sports & Entertainment
    {
        "id": "espn-top",
        "name": "ESPN Top News",
        "type": "RSS",
        "base_url": "https://www.espn.com",
        "feed_url": "https://www.espn.com/espn/rss/news",
        "country": "US",
        "language": "en",
        "category": "Sport",
        "fetch_interval": 10,
        "rate_limit": 100,
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/2/2f/ESPN_wordmark.svg"
    },
    {
        "id": "variety-news",
        "name": "Variety (Culture & Entertainment)",
        "type": "RSS",
        "base_url": "https://variety.com",
        "feed_url": "https://variety.com/feed/",
        "country": "US",
        "language": "en",
        "category": "Culture",
        "fetch_interval": 20,
        "rate_limit": 100,
        "logo_url": "https://variety.com/wp-content/themes/pmc-variety-2020/assets/public/variety-logo.svg"
    }
]
